### ISSUE TITLE
상품 개발방법 기획

### ISSUE THREAD

**Issue by Dong1333** [yulimlvphs/DY-shopping_mall#4]
**목적**
> 쇼핑몰 웹 프로젝트 개발에 필요한 상품관련 인터페이스, 클래스, 데이터베이스 구조 기획 완성

**작업내용**
> 상품 종류, 상품 관련 기능 생각해보기(CRUD), 데이터베이스 연결점, 테이블 등

**참고사항**
> 데이터베이스는 추후 완성하여도 되니 상품 종류, 기능 부터 마무리 해보기

**Comment by yulimlvphs** [comment]
수고하셨습니다.

**Comment by yulimlvphs** [comment]
이슈 종료하겠습니다.
